### ISSUE TITLE
Support SSO (Oauth2, OIDC, or SAML)

### ISSUE THREAD

**Issue by egwynn** [icbestCA/giftmanager#4]
Allow user provisioning / access to be controlled via a separate IdP.

**Comment by royaltongue** [comment]
Any updates on this? It's the last thing I need backed I can pitch using it for Christmas with my family

I was looking around and came across this: https://flask-oidc.readthedocs.io/en/latest/#

I don't have a ton of experience with python this complex overall but I thought I might as well throw some time at it when I can and see if anything works out

**Comment by icbestCA** [comment]
Hello, I've worked on something using Keycloak and OpenID Connect. I've managed to get the information of the user who logs in. I find this very complicated, I know it's authentication so it cannot be simple. It may take a bit of time since I've never worked in that.
I have some questions;
What app are you using for the auth? 
What will you use to check the user? Username or email?

Thanks for being still interested.

**Comment by royaltongue** [comment]
I've been using Authelia up until now, but I've been trying out Authentik as well. Both support OIDC so they should be compatible regardless

For the identifier, I'm thinking a username might be better? Both Authelia and Authentik require a username, but the email field is optional. Although for Authelia, I always pass 'openid' 'profile' 'email'.

There's a lot of information in [Authelia's docs](https://www.authelia.com/integration/openid-connect/introduction/) about OIDC scopes, which may help. That link is for OIDC 1, and there's an OAuth 2.0 section as well. And this is the OAuth 2.0 section [for Authentik](https://docs.goauthentik.io/docs/add-secure-apps/providers/oauth2/)

**Comment by royaltongue** [comment]
Here is my new `docker-compose`.yml:
```
services:
##################################################################
##################################################################
##################################################################
  giftmanager:
    container_name: giftmanager
    image: icbest/devgift:latest
    volumes:
      - ${dcs}/giftmanager/app/data:/app/data
      - ${dcs}/giftmanager/backup:/backup
    hostname: giftmanager
    ports:
      - 4022:5000
    restart: unless-stopped
```

And my `.env`:
```
dcs=/srv/dev-disk-by-uuid-ca6f47d3-cd3d-4acc-bb5c-53a1d0eb27e5/DockerContainerStorage

KEYCLOAK_CLIENT_ID="[redacted]"
KEYCLOAK_CLIENT_SECRET="[redacted]"
KEYCLOAK_SERVER_METADATA_URL="https://authentik.[redacted].me/application/o/giftmanager/.well-known/openid-configuration"
KEYCLOAK_LOGOUT_URL="https://authentik.[redacted].me/application/o/giftmanager/end-session/"
PRIMARY_OIDC_FIELD=email
SECONDARY_OIDC_FIELD=preferred_username
PRIMARY_DB_FIELD=email
SECONDARY_DB_FIELD=username
```

When I try to load `https://gift.[redacted].me/login_oidc`, this is the error I get:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 156, in login_oidc
    return oauth.keycloak.authorize_redirect(redirect_uri, nonce=nonce, state=state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/authlib/integrations/flask_client/apps.py", line 43, in authorize_redirect
    rv = self.create_authorization_url(redirect_uri, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/authlib/integrations/base_client/sync_app.py", line 318, in create_authorization_url
    raise RuntimeError('Missing "authorize_url" value')
RuntimeError: Missing "authorize_url" value
```

Opening a shell within the container and running `pip instrall authlib` comes back with the following: 
```
Requirement already satisfied: authlib in /usr/local/lib/python3.11/site-packages (1.3.2)
Requirement already satisfied: cryptography in /usr/local/lib/python3.11/site-packages (from authlib) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/site-packages (from cryptography->authlib) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/site-packages (from cffi>=1.12->cryptography->authlib) (2.22)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
```

Here's a picture of the configuration panel within Authentik, if it helps:
![image](https://github.com/user-attachments/assets/590f0db9-1fa3-4e63-89bb-ecc159848c80)

**Comment by icbestCA** [comment]
Hello, just installed Authentik and tested myself. Everything worked correctly. Could you just make sure your user have the right logins info (emails are similar or usernames) and you also may restart the container after updating the .env in /setup.
If still dont work, you will need to give me more infos because i dont see the problems right now.
Thanks

**Comment by royaltongue** [comment]
Unfortunately I've still not been able to get it working. So far I've tried:
* Deleting and recreating the container
* Deleting the container, deleting the folder its data was in, then recreating the container, then going to `/login_oidc`
* Again with a fresh container and folder, made a new account with the email I use for Authentik, then went to `/login_oidc`
* Changed `https://authentik.[redacted].me/application/o/giftmanager/.well-known/openid-configuration` to `https://authentik.[redacted].me/application/o/giftmanager/`

Everything still results in the same error. Can you provide the environment variables you're using for your Authentik setup?

**Comment by icbestCA** [comment]
OK, here is the detailed steps I've done:

1. Installed Authentik on a new Linode vps using this [guide](https://docs.goauthentik.io/docs/install-config/install/docker-compose)
2. Setup the admin account
3. Created a new provider called it giftmanager using OAuth2/OpenID Provider and keeping all default parameters. 
4. Ran the container of giftmanager **on a machine with public exposed ip** using the command:  `docker run -p 5055:5000 -d -v /root/data:/app/data icbest/devgift` 
![image](https://github.com/user-attachments/assets/fda1c543-81be-41c6-b2be-ac9570e7f4d1)

5. Created an account with this email (admin@email.com) and this username (icbest). Deleted default profiles.
7. **Restarted the gift app**
8. Created an account, with the same infos, on authentik. Username = icbest   Email = admin@email.com
9. Added a new app in authentik ![image](https://github.com/user-attachments/assets/dca40886-c013-4ab4-a22c-dfb61dd62130)
10. Gone to /setup in the giftmanager and added the values to .env file here they are: `KEYCLOAK_CLIENT_ID='bcG3BBvGI2upvILrdK5hnvUMCIUmx2Y04cMTck7M'`
`KEYCLOAK_CLIENT_SECRET='QrFVKTrYFf4PHPbfyKeUZVsbSiZWxaDCFw1TGmNI8iMLfEuK5mgiLgpBevvz6OnHa58Fc3aim3c5INMPT0NjDwxzz82mV6bfKpEb3Fteh4EFqRzKNGqf8AK0P9nhcVg6'`
`KEYCLOAK_SERVER_METADATA_URL='http://ip:9000/application/o/giftmanager/.well-known/openid-configuration'`
`KEYCLOAK_LOGOUT_URL='http://ip:9000/application/o/giftmanager/'`
`PRIMARY_OIDC_FIELD='email'`
`SECONDARY_OIDC_FIELD='preferred_username'`
`PRIMARY_DB_FIELD='email'`
`SECONDARY_DB_FIELD='username'`

11. **I restarted the gift container after updating the values**
12. Logout of Authentik and gift app
13. Go to /login_oidc
14. logged on Authentik using Icbest profile
15. Returned to /login_oidc get this window and click continue: ![image](https://github.com/user-attachments/assets/65941bd1-e4b1-4d1d-8883-3585a0cbfae9)
16. Then successfully logged into the gift app.

The Linode is deleted, don't worry for personal infos.
All worked while doing these steps in order. I even tested with a different username but right email, and it still worked.
Hope it works.

**Comment by royaltongue** [comment]
Oh... I didn't go into that /setup page at all. Would it make more sense to make these environment variables that can be set within the `docker.compose.yml`?

Anyway, once I set everything within that page, it srtated to work, sort of. I set the redirect URL: to `https://gift.[redacted].me/auth` at first, but Authentik gave me an error about a mismatch. I set the redirect to `*` for now and it works great otherwise

**Comment by royaltongue** [comment]
Also it would be really helpful to (maybe as an option) automatically create new GiftManager accounts if a user successfully authenticates with OIDC but does not have a user registered with GiftManager yet

**Comment by icbestCA** [comment]
I'm almost done writing everything for release. I just need to know how you want to set the environment variables in the Docker Compose. I'm not sure what the best way to do this is; any recommendations or tips are welcome.
Thanks

**Comment by royaltongue** [comment]
Within the `Dockerfile`, you can set up environment variables with defaults like this:
```
ENV TA_CACHE=/cache \
    TA_MEDIA_FOLDER=/youtube \
    TARGET_FOLDER=/youtube-processed \
    APPRISE_TRIGGER_PORT=8001 \
    TA_HELPER_SCRIPT=/app/ta-helper.py \
#
    LOGLEVEL=INFO \
    TA_SERVER=http://192.168.1.5:8000 \
    TA_TOKEN=c0ff142e1c336e9f43be560b5c942d61e7e7c7fb \
    NOTIFICATIONS_ENABLED=true \
    MAIL_USER=me@x.com \
    MAIL_RECIPIENTS=me@x.com,you@x.com \
    GENERATE_NFO=true \
    APPRISE_LINK=mailto://<username>:<password>@gmail.com \
    QUICK=true \
    CLEANUP_DELETED_VIDEOS=false \
    PUID=1049 \
    GUID=1049
    ```

**Comment by icbestCA** [comment]
Just pushed the changes, it also allow auto-registration. Sadly I didn't successfully implemented a way to put the values in the docker-compose. You will have to either modify the .env via docker exec or in /setup . I will write the documentation related to OIDC soon. Thanks for the help.

**Comment by royaltongue** [comment]
Thank you!

**Comment by vfedetz** [comment]
Tried configuring Google as my OIDC provider, but am getting this error when attempting to load https://gift.[redacted].net/login_oidc

`172.27.0.1 - - [22/Nov/2024 01:57:59] "GET /login_oidc HTTP/1.1" 500 -

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__

    return self.wsgi_app(environ, start_response)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app

    response = self.handle_exception(e)

               ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app

    response = self.full_dispatch_request()

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request

    rv = self.handle_user_exception(e)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request

    rv = self.dispatch_request()

         ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/app.py", line 152, in login_oidc

    nonce = secrets.token_urlsafe(16)

            ^^^^^^^^^^^^^^^^^^^^^^^^^

NameError: name 'secrets' is not defined`

Here is my .env file:

`FEED_SEND=''
MAILJET_API_KEY=''
MAILJET_API_SECRET=''
SECRET_KEY='changethis'
SYSTEM_EMAIL=''
DELETE_DAYS='30'
OIDC_CLIENT_ID='[redacted]'
OIDC_CLIENT_SECRET='[redacted]'
OIDC_SERVER_METADATA_URL='https://accounts.google.com/.well-known/openid-configuration'
OIDC_LOGOUT_URL='https://accounts.google.com/Logout'
PRIMARY_OIDC_FIELD='email'
SECONDARY_OIDC_FIELD='preferred_username'
PRIMARY_DB_FIELD='email'
SECONDARY_DB_FIELD='username'
ENABLE_AUTO_REGISTRATION='true'`

**Comment by icbestCA** [comment]
Yeah, good. Now corrected; see v.1.0.2
Docker latest and 1.0.2 now available.
Thanks

**Comment by icbestCA** [comment]
It seem that there is a small bug with the **auto registration feature**. I'm on it. I still don't know the cause.

**Comment by icbestCA** [comment]
The issue is now fixed.
It was only the docker json url that wasn't referenced correctly in the setup_profile route.
`with open(app.config['USERS_FILE'], "w") as file:
            json.dump(users, file, indent=4)`

See v1.0.3
Image upload to docker hub.

**Comment by icbestCA** [comment]
Could you provide the users.json file? And what version are you on?? I'm on 2.6.2 with a keycloak instance for OIDC and I don't have any issue.
